trigger:
- main

pool:
  name: Default

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: pip install poetry
  displayName: 'Install Poetry'

- script: poetry install --no-root
  displayName: 'Install Dependencies'

- script: poetry run pytest
  displayName: 'Run Tests'